### PR TITLE
Corrected R package check errors

### PR DESCRIPTION
**Pull request by lm186**
Jacopo,

I used Rstudio to compile the package and it gave me some errors regarding the examples in the manual. 

-Li

### CODE REVIEW

**Comment by lm186** [comment]
I did this two weeks ago and i see that you have updated the package two days ago. It looks like you have already corrected two of the three errors.

**Comment by jacsor** [comment]
Have you tried to install the package using devtools?
install.packages('devtools')
library('devtools')
devtools::install_github('MRS', 'jacsor')

**Comment by lm186** [comment]
yes. i tried. installation is no problem. when running some of the examples
in the manual files there were three errors, which the commits corrected.
but i see that you have corrected some of these errors already.

On Tue, Nov 3, 2015 at 9:07 PM, Jacopo Soriano notifications@github.com
wrote:

> Have you tried to install the package using devtools?
> install.packages('devtools')
> library('devtools')
> devtools::install_github('MRS', 'jacsor')
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jacsor/MRS/pull/1#issuecomment-153547919.

## 

Li Ma
Assistant Professor
Department of Statistical Science
Duke University
http://stat.duke.edu/~lm186/

**Comment by lm186** [comment]
Hi Jacopo,

The updated version of MRS compiles and checks with no problem in RStudio on my computer. So I will remove the pull requests. It looks like your cleaning has addressed all of the problems. 

-Li

**Pull request closed without merging**
